_wandb:
    value:
        cli_version: 0.22.0
        e:
            kixgda81dl6z9nailrqdzd12ijteeyc6:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "982830919680"
                email: c612401914@tokushima-u.ac.jp
                executable: /home/kato/programs/VisionConditionedASR/bin/python
                git:
                    commit: 080f64cbc404ea5ee1ef643467397437e767b06b
                    remote: git@github.com:AoiNoGeso/VisionConditionedASR.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-9acdd329-e7f3-3e13-aed7-16fd24a89606
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-fc38a2be-0bac-7a8a-69c1-699942a8ccac
                host: gemini
                memory:
                    total: "135006765056"
                os: Linux-6.8.0-84-generic-x86_64-with-glibc2.35
                program: /home/kato/programs/VisionConditionedASR/src/train.py
                python: CPython 3.10.13
                root: /home/kato/programs/VisionConditionedASR/src
                startedAt: "2025-10-02T07:16:01.561486Z"
                writerId: kixgda81dl6z9nailrqdzd12ijteeyc6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 16
            "4": 3.10.13
            "5": 0.22.0
            "6": 4.56.2
            "12": 0.22.0
            "13": linux-x86_64
audio_dir:
    value: ../../Datasets/SpokenCOCO
batch_size:
    value: 8
checkpoint_dir:
    value: ../checkpoints
device:
    value: cuda:1
freeze_audio_encoder:
    value: true
freeze_cross_attention:
    value: false
freeze_vision_encoder:
    value: true
gradient_clip:
    value: 1
hidden_dim:
    value: 256
image_dir:
    value: ../../Datasets/stair_captions/images
learning_rate:
    value: 0.0001
log_step:
    value: 50
max_audio_length:
    value: 10
num_epochs:
    value: 10
num_heads:
    value: 2
num_workers:
    value: 4
save_epoch:
    value: 1
train_json:
    value: ../../Datasets/SpokenCOCO/SpokenCOCO_train_fixed.json
use_wandb:
    value: true
val_json:
    value: ../../Datasets/SpokenCOCO/SpokenCOCO_val_fixed.json
validate_epoch:
    value: 1
validate_files:
    value: true
vocab_size:
    value: null
wandb_project:
    value: VisionConditionedASR
warmup_steps:
    value: 1000
weight_decay:
    value: 1e-05
